services:
  beyondallinfo:
    container_name: beyondallinfo
    build:
      dockerfile: ./Dockerfile
    image: furyhawk/beyondallinfo:latest
    hostname: beyondallinfo
    ports:
      - "${BAI_PORT:-8501}:8501"
    restart: unless-stopped

