version: "3.7"
services:
  beyondallinfo:
    container_name: beyondallinfo
    build:
      dockerfile: ./Dockerfile
    image: beyondallinfo:latest
    hostname: beyondallinfo
    ports:
      - "8501:8501"
    restart: unless-stopped

