version: "3.7"
networks:
  web:
    external: true
  internal:
    external: false
    driver: bridge

services:
  caddy:
    container_name: caddy
    image: caddy:2-alpine
    ports:
      - "${CADDY_PORT:-80}:80"
      - "${CADDY_PORT_SSL:-443}:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - web
      - internal
    restart: unless-stopped

  beyondallinfo:
    container_name: beyondallinfo
    build:
      dockerfile: ./Dockerfile
    image: furyhawk/beyondallinfo:latest
    hostname: beyondallinfo
    ports:
      - "${BAI_PORT:-8501}:8501"
    restart: unless-stopped

