version: "3.7"
services:
  beyondallreason:
    container_name: beyondallreason
    build:
      dockerfile: ./Dockerfile
    image: beyondallreason:latest
    ports:
      - "8501:8501"
    restart: unless-stopped
    networks:
      beyondallreason-network:
        aliases:
          - beyondallreason
