version: "3.7"
services:
  beyondallinfo:
    container_name: beyondallinfo
    build:
      dockerfile: ./Dockerfile
    image: furyhawk/beyondallinfo:latest
    hostname: beyondallinfo
    ports:
      - "${PORT:-8501}:${PORT:-8501}"
    restart: unless-stopped

